export enum ActionType {
  SEARCH_IMAGES = "SEARCH_IMAGES",
  SEARCH_IMAGES_SUCCESS = "SEARCH_IMAGES_SUCCESS",
  SEARCH_IMAGES_ERROR = "SEARCH_IMAGES_ERROR",
  SEARCH_MORE_IMAGES = "SEARCH_MORE_IMAGES",
  SEARCH_MORE_IMAGES_SUCCESS = "SEARCH_MORE_IMAGES_SUCCESS",
  SEARCH_MORE_IMAGES_ERROR = "SEARCH_MORE_IMAGES_ERROR",
}
